services:
  db:
    image: postgres:16-alpine
    network_mode: host
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /srv/_actixweb-askama-seaorm_db:/var/lib/postgresql/data
